# Generated by Django 4.2.2 on 2023-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword'),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
    ]
